{"name": "Проверка на ошибку при использовании неверных данных", "status": "passed", "description": "Проверяем, что пользователь с некорректными данными не может авторизоваться", "start": 1724672766949, "stop": 1724672767960, "uuid": "6dfdca94-9c73-420a-a67f-d0ef13efa389", "historyId": "08634cc7e2fe52868ac90e98c3a2e9cc", "testCaseId": "08634cc7e2fe52868ac90e98c3a2e9cc", "fullName": "tests.test_login.TestLogin#test_login_incorrect_data_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-ILSU1PHQ"}, {"name": "thread", "value": "3272-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}